
networks:
  guacnetwork_compose:
    driver: bridge

services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "MiEmpresa"
      LDAP_DOMAIN: "dominio.local"
      LDAP_ADMIN_PASSWORD: adminpassword
    ports:
      - "389:389"
      - "636:636"
    networks:
    - guacnetwork_compose
    restart: always

  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
    networks:
      - guacnetwork_compose
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw

  postgres:
    container_name: postgres_guacamole_compose
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'Qaz9900.'
      POSTGRES_USER: guacamole_user
    image: postgres:15.2-alpine
    networks:
      - guacnetwork_compose
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:z
    - ./data:/var/lib/postgresql/data:Z

  guacamole:
    container_name: guacamole_compose
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: Qaz9900.
      POSTGRES_USER: guacamole_user
      LDAP_HOSTNAME: ldap
      LDAP_PORT: 389
      LDAP_USER_BASE_DN: ou=people,dc=dominio,dc=local
      LDAP_USERNAME_ATTRIBUTE: uid
      LDAP_CONFIG_BASE_DN: dc=dominio,dc=local
      LDAP_ENCRYPTION_METHOD: none
      LDAP_SEARCH_BIND_DN: cn=admin,dc=dominio,dc=local
      LDAP_SEARCH_BIND_PASSWORD: adminpassword
    image: guacamole/guacamole
    links:
    - guacd
    networks:
      guacnetwork_compose:
    ports:
    - 8080/tcp
    restart: always

  nginx:
   container_name: nginx_guacamole_compose
   restart: always
   image: nginx:latest
   volumes:
   - ./nginx/templates:/etc/nginx/templates:ro
   - ./nginx/ssl/self.cert:/etc/nginx/ssl/self.cert:ro
   - ./nginx/ssl/self-ssl.key:/etc/nginx/ssl/self-ssl.key:ro
   ports:
   - 8443:443
   networks:
     - guacnetwork_compose

  # ubuntu con SSH
  ubuntu-ssh:
   container_name: ubuntu_ssh_compose
   image: pabloarriola/ubuntu-ssh
   networks:
   - guacnetwork_compose
   restart: always
   ports:
   - 2222:22

  vnc-ubuntu:
   container_name: vnc_ubuntu_compose
   image: dorowu/ubuntu-desktop-lxde-vnc
   environment:
   - USER=ubuntu
   - PASSWORD=ubuntu
   - RESOLUTION=1280x800
   ports:
   - "5900:5900"   # <— Esto es imprescindible
   - "6901:6901"   # opcional, si quieres noVNC en http://host:6901
   networks:
   - guacnetwork_compose
   restart: always
